spring.application.name=student-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/Your_Database
spring.datasource.username=Your_Username
spring.datasource.password=Your_Password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

app.jwt.secret=Your_Key
app.jwt.expiration=86400000